spring:
  application:
    name: registry-service
  profiles:
    active: native
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
    url: jdbc:postgresql://localhost/registry-service
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
